keys:
  - &pluto age10s0ym34x66hshr35qhgm2lrmrhm9x3d7zwd55e50yr6jkkwjyqss7mtt7u
creation_rules:
  - path_regex: systems/x86_64-linux/pluto/secrets.yaml$
    key_groups:
      - age:
          - *pluto
  - path_regex: homes/x86_64-linux/jaugusto/secrets.yaml$
    key_groups:
      - age:
          - *pluto
